/**
 * AI-Enhanced Search Planner
 * 
 * Uses LLM to analyze user intent and generate optimized search strategies
 * before executing product searches. This improves search quality by:
 * - Understanding budget, features, and preferences
 * - Generating specific product model queries
 * - Creating weighted candidate queries
 * - Providing fallback strategies
 */

import { generateText, type LanguageModel } from 'ai';
import { createGoogleGenerativeAI } from '@ai-sdk/google';
import { z } from 'zod';
import { getAgentConfig } from '../../../config';

// ============================================================================
// Types and Schemas
// ============================================================================

/**
 * Budget range for product search
 * Note: nullable() allows LLM to return null instead of omitting the field
 */
export const BudgetSchema = z.object({
  min: z.number().nullable().optional().describe('Minimum budget in INR'),
  max: z.number().nullable().optional().describe('Maximum budget in INR'),
  approximate: z.number().nullable().optional().describe('Approximate/target budget in INR'),
}).describe('Budget constraints for search');

/**
 * Brand preferences
 */
export const BrandPreferencesSchema = z.object({
  preferred: z.array(z.string()).optional().describe('Preferred brands'),
  avoid: z.array(z.string()).optional().describe('Brands to avoid'),
}).describe('Brand preferences');

/**
 * Single candidate search query with weight
 */
export const CandidateQuerySchema = z.object({
  query: z.string().describe('Specific search query (e.g., "Realme 11 6GB 128GB")'),
  weight: z.number().min(0).max(1).describe('Relevance weight (0.0 to 1.0)'),
  rationale: z.string().optional().describe('Why this query is relevant'),
}).describe('A candidate search query with priority weight');

/**
 * Complete search plan output from LLM
 */
export const PlannerOutputSchema = z.object({
  queryIntent: z.string().describe('User\'s search intent in plain language'),
  budget: BudgetSchema.optional(),
  priorities: z.array(z.string()).describe('Key features/priorities (e.g., ["camera", "battery"])'),
  brands: BrandPreferencesSchema.optional(),
  candidateQueries: z.array(CandidateQuerySchema)
    .min(1)
    .max(6)
    .describe('3-6 specific product queries to search'),
  marketContext: z.string().optional().describe('Indian market context/notes'),
}).describe('Search strategy plan generated by LLM');

export type Budget = z.infer<typeof BudgetSchema>;
export type BrandPreferences = z.infer<typeof BrandPreferencesSchema>;
export type CandidateQuery = z.infer<typeof CandidateQuerySchema>;
export type PlannerOutput = z.infer<typeof PlannerOutputSchema>;

/**
 * Conversation context for planner
 */
export interface PlannerContext {
  previousQueries?: string[];
  preferredBrands?: string[];
  budgetHistory?: number[];
  productCategory?: string;
}

/**
 * Options for search planner
 */
export interface PlanSearchOptions {
  userMessage: string;
  context?: PlannerContext;
  maxCandidates?: number; // 1-6, default 5
  temperature?: number; // LLM temperature, default 0.1
  model?: string; // Override default model
}

// ============================================================================
// LLM Search Planner
// ============================================================================

/**
 * Plan search strategy using LLM reasoning
 */
export async function planSearch(options: PlanSearchOptions): Promise<PlannerOutput> {
  const {
    userMessage,
    context = {},
    maxCandidates = 5,
    temperature = 0.1,
  } = options;

  try {
    const model = await getPlannerModel(options.model);
    
    const prompt = buildPlannerPrompt(userMessage, context, maxCandidates);
    
    const { text } = await generateText({
      model,
      prompt,
      temperature,
    });

    // Check if response is empty
    if (!text || text.trim().length === 0) {
      throw new Error('LLM returned empty response');
    }

    // Parse and validate LLM output
    const parsed = parseAndValidatePlannerOutput(text);
    
    // Normalize weights to sum to 1.0
    const normalized = normalizeCandidateWeights(parsed);
    
    return normalized;
  } catch (error: any) {
    console.warn(`⚠️  LLM planner failed: ${error.message}. Using fallback planner.`);
    
    // Fallback to heuristic planner
    return fallbackPlanner(userMessage, context, maxCandidates);
  }
}

/**
 * Build prompt for LLM planner
 */
function buildPlannerPrompt(
  userMessage: string,
  context: PlannerContext,
  maxCandidates: number
): string {
  const contextInfo = formatContextInfo(context);
  
  return `You are an expert shopping search planner for the Indian market. Your job is to analyze a user's product search request and create an optimal search strategy.

USER REQUEST:
"${userMessage}"

${contextInfo}

ANALYZE THE REQUEST AND CREATE A SEARCH PLAN:

1. **Understand Intent**: What product does the user want? What are their priorities?

2. **Extract Budget**: 
   - Look for numbers followed by "k" (e.g., "20k" = ₹20,000)
   - Phrases like "under X", "around X", "X to Y"
   - If no budget mentioned, infer reasonable range for product category

3. **Identify Priorities**: What features matter most? (e.g., camera, battery, gaming, portability)

4. **Suggest Brands**: Based on budget and Indian market, which brands are best value?

5. **Generate ${maxCandidates} Candidate Queries**: 
   - Each query should be SPECIFIC (actual model names, not generic)
   - Format: "[Brand] [Model] [Key Specs]" (e.g., "Realme 11 6GB 128GB")
   - Weight by relevance (higher weight = better match for user needs)
   - Weights must sum to 1.0

IMPORTANT GUIDELINES:
- Use actual product model names popular in India (2024-2025)
- Consider Indian market leaders: Realme, Xiaomi, Samsung, OnePlus (phones); HP, Lenovo, ASUS (laptops)
- Budget-conscious: Indians prefer value-for-money
- Include variant specs (RAM/storage for phones/laptops, screen size, etc.)
- Weights should reflect: brand reputation + spec match + price-to-value ratio

RESPOND WITH VALID JSON ONLY (no markdown, no explanation):

{
  "queryIntent": "Brief description of what user wants",
  "budget": {
    "min": 15000,  // optional
    "max": 25000,  // optional
    "approximate": 20000  // optional
  },
  "priorities": ["camera", "battery", "5G"],
  "brands": {
    "preferred": ["Realme", "Xiaomi"],
    "avoid": []  // optional
  },
  "candidateQueries": [
    {
      "query": "Realme 11 5G 6GB 128GB",
      "weight": 0.35,
      "rationale": "Best camera in budget, great battery"
    },
    {
      "query": "Xiaomi Redmi Note 12 Pro 6GB 128GB",
      "weight": 0.30,
      "rationale": "Excellent display, good all-rounder"
    },
    {
      "query": "Samsung Galaxy M34 5G 6GB 128GB",
      "weight": 0.20,
      "rationale": "Premium brand, reliable"
    },
    {
      "query": "POCO X5 Pro 5G 6GB 128GB",
      "weight": 0.15,
      "rationale": "Gaming performance, value"
    }
  ],
  "marketContext": "₹20k segment is competitive with 5G, 50MP+ cameras standard"
}

NOW ANALYZE THE REQUEST AND RESPOND:`;
}

/**
 * Format context information for prompt
 */
function formatContextInfo(context: PlannerContext): string {
  const parts: string[] = [];
  
  if (context.previousQueries && context.previousQueries.length > 0) {
    parts.push(`PREVIOUS SEARCHES:\n${context.previousQueries.join('\n')}`);
  }
  
  if (context.preferredBrands && context.preferredBrands.length > 0) {
    parts.push(`USER PREFERS BRANDS: ${context.preferredBrands.join(', ')}`);
  }
  
  if (context.budgetHistory && context.budgetHistory.length > 0) {
    const avgBudget = Math.round(
      context.budgetHistory.reduce((a, b) => a + b, 0) / context.budgetHistory.length
    );
    parts.push(`TYPICAL BUDGET: ~₹${avgBudget.toLocaleString('en-IN')}`);
  }
  
  if (context.productCategory) {
    parts.push(`PRODUCT CATEGORY: ${context.productCategory}`);
  }
  
  return parts.length > 0 ? `\nCONTEXT:\n${parts.join('\n')}\n` : '';
}

/**
 * Parse and validate LLM JSON output
 */
function parseAndValidatePlannerOutput(text: string): PlannerOutput {
  // Extract JSON from response (remove markdown code blocks if present)
  let jsonStr = text.trim();
  
  // Remove markdown code blocks
  jsonStr = jsonStr.replace(/^```json?\s*/i, '').replace(/```\s*$/, '');
  
  // Find JSON object
  const jsonMatch = jsonStr.match(/\{[\s\S]*\}/);
  if (!jsonMatch) {
    throw new Error('No JSON object found in LLM response');
  }
  
  const parsed = JSON.parse(jsonMatch[0]);
  
  // Validate with Zod schema
  const validated = PlannerOutputSchema.parse(parsed);
  
  return validated;
}

/**
 * Normalize candidate query weights to sum to 1.0
 */
export function normalizeCandidateWeights(plan: PlannerOutput): PlannerOutput {
  const totalWeight = plan.candidateQueries.reduce((sum, cq) => sum + cq.weight, 0);
  
  if (totalWeight === 0) {
    // Equal weights if all zero
    const equalWeight = 1.0 / plan.candidateQueries.length;
    plan.candidateQueries.forEach(cq => {
      cq.weight = equalWeight;
    });
  } else if (Math.abs(totalWeight - 1.0) > 0.01) {
    // Normalize to sum to 1.0
    plan.candidateQueries.forEach(cq => {
      cq.weight = cq.weight / totalWeight;
    });
  }
  
  return plan;
}

// ============================================================================
// Fallback Heuristic Planner
// ============================================================================

/**
 * Fallback planner when LLM fails - uses heuristics
 */
export function fallbackPlanner(
  userMessage: string,
  context: PlannerContext,
  maxCandidates: number
): PlannerOutput {
  // Extract budget
  const budget = extractBudget(userMessage);
  
  // Detect product category
  const category = detectCategory(userMessage);
  
  // Extract brand mentions
  const brands = extractBrands(userMessage, category);
  
  // Generate candidate queries
  const candidates = generateFallbackCandidates(
    userMessage,
    category,
    budget,
    brands,
    maxCandidates
  );
  
  return {
    queryIntent: `Search for ${category} ${budget.max ? `under ₹${budget.max}` : ''}`,
    budget: Object.keys(budget).length > 0 ? budget : undefined,
    priorities: detectPriorities(userMessage, category),
    brands: brands.length > 0 ? { preferred: brands } : undefined,
    candidateQueries: candidates,
    marketContext: 'Using fallback heuristic planner',
  };
}

/**
 * Extract budget from user message
 */
function extractBudget(message: string): Budget {
  const budget: Budget = {};
  
  // Pattern: "under 50000", "below 50k"
  const underMatch = message.match(/(?:under|below|max|upto|up to)\s*(?:₹|rs\.?|inr)?\s*(\d+)k?/i);
  if (underMatch?.[1]) {
    const value = parseFloat(underMatch[1]);
    budget.max = value > 100 ? value : value * 1000;
  }
  
  // Pattern: "around 40000", "about 40k"
  const aroundMatch = message.match(/(?:around|about|approx|near)\s*(?:₹|rs\.?|inr)?\s*(\d+)k?/i);
  if (aroundMatch?.[1]) {
    const value = parseFloat(aroundMatch[1]);
    budget.approximate = value > 100 ? value : value * 1000;
  }
  
  // Pattern: "25000 to 35000", "25k-35k"
  const rangeMatch = message.match(/(\d+)k?\s*(?:to|-)\s*(\d+)k?/i);
  if (rangeMatch?.[1] && rangeMatch[2]) {
    const min = parseFloat(rangeMatch[1]);
    const max = parseFloat(rangeMatch[2]);
    budget.min = min > 100 ? min : min * 1000;
    budget.max = max > 100 ? max : max * 1000;
  }
  
  return budget;
}

/**
 * Detect product category
 */
function detectCategory(message: string): string {
  const msg = message.toLowerCase();
  
  if (/\b(phone|mobile|smartphone)\b/.test(msg)) return 'smartphone';
  if (/\b(laptop|notebook)\b/.test(msg)) return 'laptop';
  if (/\b(tablet|ipad)\b/.test(msg)) return 'tablet';
  if (/\b(headphone|earphone|earbud|airpod)\b/.test(msg)) return 'audio device';
  if (/\b(watch|smartwatch)\b/.test(msg)) return 'smartwatch';
  if (/\b(tv|television)\b/.test(msg)) return 'television';
  if (/\b(camera)\b/.test(msg)) return 'camera';
  if (/\b(gaming|console|ps5|xbox)\b/.test(msg)) return 'gaming';
  
  return 'product';
}

/**
 * Extract brand mentions
 */
function extractBrands(message: string, category: string): string[] {
  const brands: string[] = [];
  const msg = message.toLowerCase();
  
  // Common brands by category
  const brandsByCategory: Record<string, string[]> = {
    smartphone: ['realme', 'xiaomi', 'samsung', 'oneplus', 'poco', 'vivo', 'oppo', 'apple', 'nothing'],
    laptop: ['hp', 'dell', 'lenovo', 'asus', 'acer', 'apple', 'msi', 'lg'],
    tablet: ['samsung', 'apple', 'lenovo', 'xiaomi'],
    'audio device': ['boat', 'oneplus', 'realme', 'sony', 'jbl', 'bose', 'apple'],
    smartwatch: ['noise', 'boat', 'fire-boltt', 'samsung', 'apple', 'amazfit'],
    television: ['samsung', 'lg', 'sony', 'mi', 'oneplus', 'tcl'],
  };
  
  const possibleBrands = brandsByCategory[category] || [];
  
  for (const brand of possibleBrands) {
    if (msg.includes(brand)) {
      brands.push(brand.charAt(0).toUpperCase() + brand.slice(1));
    }
  }
  
  return brands;
}

/**
 * Detect feature priorities from message
 */
function detectPriorities(message: string, category: string): string[] {
  const priorities: string[] = [];
  const msg = message.toLowerCase();
  
  // Common priorities
  if (/\b(camera|photo|picture)\b/.test(msg)) priorities.push('camera');
  if (/\b(battery|charge)\b/.test(msg)) priorities.push('battery life');
  if (/\b(gaming|game|fps)\b/.test(msg)) priorities.push('gaming performance');
  if (/\b(display|screen|amoled)\b/.test(msg)) priorities.push('display quality');
  if (/\b(fast|quick|speed|performance)\b/.test(msg)) priorities.push('performance');
  if (/\b(storage|gb|memory)\b/.test(msg)) priorities.push('storage');
  if (/\b(5g|network)\b/.test(msg)) priorities.push('5G connectivity');
  if (/\b(light|portable|thin)\b/.test(msg)) priorities.push('portability');
  
  // Default priorities by category
  if (priorities.length === 0) {
    const defaultPriorities: Record<string, string[]> = {
      smartphone: ['camera', 'battery life', 'performance'],
      laptop: ['performance', 'portability', 'battery life'],
      'audio device': ['sound quality', 'battery life', 'comfort'],
      smartwatch: ['battery life', 'fitness tracking', 'display'],
    };
    
    priorities.push(...(defaultPriorities[category] || ['quality', 'value for money']));
  }
  
  return priorities;
}

/**
 * Generate fallback candidate queries
 */
function generateFallbackCandidates(
  userMessage: string,
  category: string,
  budget: Budget,
  brands: string[],
  maxCandidates: number
): CandidateQuery[] {
  const candidates: CandidateQuery[] = [];
  
  // Build base query
  const budgetStr = budget.max 
    ? `under ${budget.max}` 
    : budget.approximate 
    ? `around ${budget.approximate}` 
    : '';
  
  // Primary query: user message + India
  candidates.push({
    query: `${userMessage} India`,
    weight: 0.4,
    rationale: 'Direct user query with India context',
  });
  
  // Secondary query: category + budget + India
  if (budgetStr) {
    candidates.push({
      query: `${category} ${budgetStr} India`,
      weight: 0.3,
      rationale: 'Category-focused with budget',
    });
  }
  
  // Brand-specific queries
  if (brands.length > 0) {
    const brandWeight = 0.3 / brands.length;
    brands.slice(0, maxCandidates - candidates.length).forEach(brand => {
      candidates.push({
        query: `${brand} ${category} ${budgetStr} India`.trim(),
        weight: brandWeight,
        rationale: `${brand} specific search`,
      });
    });
  }
  
  // Generic fallback if we don't have enough
  if (candidates.length < 2) {
    candidates.push({
      query: `best ${category} India ${new Date().getFullYear()}`,
      weight: 0.3,
      rationale: 'Generic best-of search',
    });
  }
  
  // Limit to maxCandidates
  const limited = candidates.slice(0, maxCandidates);
  
  // Normalize weights
  return normalizeCandidateWeights({ 
    queryIntent: '', 
    priorities: [], 
    candidateQueries: limited 
  }).candidateQueries;
}

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Format planner output for display
 */
export function formatPlannerExplanation(plan: PlannerOutput): string {
  const lines: string[] = [];
  
  lines.push(`🎯 Search Strategy:`);
  lines.push(`   Intent: ${plan.queryIntent}`);
  
  if (plan.budget) {
    const budgetStr = plan.budget.max 
      ? `₹${plan.budget.max.toLocaleString('en-IN')} max`
      : plan.budget.approximate 
      ? `~₹${plan.budget.approximate.toLocaleString('en-IN')}`
      : plan.budget.min 
      ? `₹${plan.budget.min.toLocaleString('en-IN')}+`
      : 'Flexible';
    lines.push(`   Budget: ${budgetStr}`);
  }
  
  if (plan.priorities.length > 0) {
    lines.push(`   Priorities: ${plan.priorities.join(', ')}`);
  }
  
  if (plan.brands?.preferred && plan.brands.preferred.length > 0) {
    lines.push(`   Brands: ${plan.brands.preferred.join(', ')}`);
  }
  
  lines.push(`   Strategies (${plan.candidateQueries.length}):`);
  plan.candidateQueries.forEach((cq, i) => {
    const percent = (cq.weight * 100).toFixed(0);
    lines.push(`     ${i + 1}. "${cq.query}" (${percent}%)`);
  });
  
  return lines.join('\n');
}

/**
 * Extract search parameters from planner output
 */
export function extractSearchParams(plan: PlannerOutput): {
  minPrice?: number | undefined;
  maxPrice?: number | undefined;
  location: string;
} {
  const min = plan.budget?.min;
  const max = plan.budget?.max;

  return {
    minPrice: typeof min === 'number' ? min : undefined,
    maxPrice: typeof max === 'number' ? max : undefined,
    location: 'India',
  };
}

let cachedPlannerModel: LanguageModel | null = null;
let cachedPlannerModelName: string | null = null;
let cachedProvider: ReturnType<typeof createGoogleGenerativeAI> | null = null;
let cachedProviderKey: string | null = null;

function getPlannerProvider(apiKey: string) {
  if (!cachedProvider || cachedProviderKey !== apiKey) {
    cachedProvider = createGoogleGenerativeAI({ apiKey });
    cachedProviderKey = apiKey;
    cachedPlannerModel = null;
    cachedPlannerModelName = null;
  }
  return cachedProvider;
}

async function getPlannerModel(modelOverride?: string): Promise<LanguageModel> {
  const { apiKey, model: defaultModelName } = getAgentConfig('agent5');
  const provider = getPlannerProvider(apiKey);

  if (!modelOverride) {
    if (!cachedPlannerModel || cachedPlannerModelName !== defaultModelName) {
      cachedPlannerModel = provider(defaultModelName);
      cachedPlannerModelName = defaultModelName;
    }
    return cachedPlannerModel;
  }

  return provider(modelOverride);
}
